"use client";
import {useEffect,useRef,useState} from "react";
type Job={id:string;state:string;message:string|null;printify_order_id:string|null;updated_at:string};
type Status={jobs:Job[];lastRun:{completedAt:string;result:{error?:string}}|null;error?:string};
const labels:Record<string,string>={ready:"Ready to prepare",created:"Prepared in Printify","awaiting-provider":"Printify is preparing",submitting:"Submitting order",uncertain:"Waiting for confirmation",release_pending:"Requesting production",release_uncertain:"Checking production request",submitted:"Sent to production",complete:"Shipped",blocked:"Needs attention"};
export default function AutomaticOrderStatus(){
 const [status,setStatus]=useState<Status|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");const lock=useRef(false);
 useEffect(()=>{let active=true;async function refresh(){try{const r=await fetch("/api/checkout?orders=1",{cache:"no-store"}),data=await r.json() as Status;if(!r.ok)throw new Error(data.error||"Could not read order status.");if(active)setStatus(data);}catch(e){if(active)setError((e as Error).message);}}void refresh();const timer=setInterval(refresh,60000);return()=>{active=false;clearInterval(timer);};},[]);
 async function process(){if(lock.current)return;lock.current=true;setBusy(true);setError("");try{const r=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"process"})}),result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||"Could not check paid orders.");const response=await fetch("/api/checkout?orders=1",{cache:"no-store"}),data=await response.json() as Status;if(!response.ok)throw new Error(data.error||"Could not read order status.");setStatus(data);}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 return <section className="setup-card"><p className="eyebrow">CUSTOM CHECKOUT</p><h2>Your jerseys, sent with your artwork.</h2><p>New custom checkouts upload all five print panels before payment. Paid orders use those exact products and sizes. Order status appears here after the payment check runs.</p><button className="primary-button" disabled={busy} onClick={process}>{busy?"Checking payment and Printify…":"Check paid orders now"}</button>{(error||status?.lastRun?.result?.error)&&<p className="connection-error" role="alert">{error||status?.lastRun?.result.error}</p>}{status?.lastRun&&<p className="fine-print">Last payment check: {new Date(status.lastRun.completedAt).toLocaleString()}</p>}{status&&!status.jobs.length&&<p>No new paid custom orders have been processed yet.</p>}{status?.jobs.map(job=><article className="order-line" key={job.id}><div><h3>Order {job.id.split("/").pop()}</h3><strong>{labels[job.state]??job.state}</strong>{job.message&&<p>{job.message}</p>}{job.printify_order_id&&<p>Printify order: {job.printify_order_id}</p>}</div><a className="text-link" href={"https://admin.shopify.com/store/eewwjf-tt/orders/"+job.id.split("/").pop()} target="_blank" rel="noreferrer">Open Shopify order ↗</a></article>)}<a className="text-link" href="https://printify.com/app/store/orders" target="_blank" rel="noreferrer">Printify orders and tracking ↗</a><p className="fine-print">Shipping progress is available in Printify. Shopify tracking updates are not automated yet. Earlier checkout previews remain in the review section below.</p></section>;
}
