"use client";
import {useRef,useState} from "react";
import type {CheckoutItem,CheckoutResult} from "@/lib/checkout-types";
export default function CheckoutPreview({items,onSaved}:{items:CheckoutItem[];onSaved?:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<(CheckoutResult&{fingerprint:string})|null>(null),attempt=useRef<{id:string;fingerprint:string}|null>(null),lock=useRef(false);
 const clean=items.map(({teamId,size,quantity,config})=>({teamId,size,quantity,config})),fingerprint=JSON.stringify(clean);
 async function preview(){if(lock.current)return;lock.current=true;setBusy(true);setError("");try{if(attempt.current?.fingerprint!==fingerprint)attempt.current={id:crypto.randomUUID(),fingerprint};const r=await fetch("/api/shopify-checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"preview",checkout:{id:attempt.current.id,items:clean}})}),data=await r.json() as CheckoutResult&{error?:string};if(!r.ok)throw new Error(data.error||"Could not prepare checkout.");setResult({...data,fingerprint});onSaved?.();}catch(e){setError((e as Error).message);}finally{setBusy(false);lock.current=false;}}
 const totalQuantity=items.reduce((total,item)=>total+item.quantity,0);
 return <div className="checkout-preview"><p className="checkout-quantity-summary" aria-live="polite"><strong>Checkout quantity: {totalQuantity} {totalQuantity===1?"jersey":"jerseys"}</strong></p><button className="primary-button full" disabled={busy||!items.length} onClick={preview}>{busy?"Saving designs and preparing checkout…":"Prepare Shopify checkout preview"}</button>{error&&<p role="alert" className="connection-error">{error}</p>}{result?.fingerprint===fingerprint&&<><p>Your designs are saved under Drafts → Custom selection. Shopify has the selected sizes, quantities and design references.</p><a className="secondary-button full" href={result.checkoutUrl} target="_blank" rel="noreferrer">Open checkout for {totalQuantity} {totalQuantity===1?"jersey":"jerseys"} ↗</a></>}<p className="fine-print">After changing your bag, prepare a new checkout preview and use its new link. Previously opened Shopify tabs keep their earlier quantities. Admin test only; do not complete payment yet.</p><a className="text-link" href="/connect#checkout">Published product and checkout settings</a></div>;
}
