"use client";
import {useEffect,useRef,useState} from "react";
import {CheckCircle2,ExternalLink,RefreshCw} from "lucide-react";
import {themeLabel} from "@/lib/catalog";
import type {FulfillmentReview as Review,FulfillmentLine} from "@/lib/fulfillment-types";
import type {Transfer} from "@/lib/printify-transfer-types";
import Jersey3D from "./jersey-3d";
const printifyOrders="https://printify.com/app/store/orders";
export default function FulfillmentReview(){
 const [review,setReview]=useState<Review|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[manualId,setManualId]=useState(""),[confirmed,setConfirmed]=useState(false),[open,setOpen]=useState<string|null>(null),lock=useRef(false);
 const orderId=()=>new URLSearchParams(window.location.search).get("order")??"";
 async function load(page=1,useManual=false){if(lock.current)return;lock.current=true;setBusy(true);setError("");setConfirmed(false);try{
  const q=new URLSearchParams({order:orderId(),page:String(page)});if(useManual&&manualId.trim())q.set("printifyOrder",manualId.trim());
  const r=await fetch("/api/fulfillment?"+q,{cache:"no-store"}),data=await r.json() as Review&{error?:string};if(!r.ok)throw new Error(data.error||"Could not check fulfillment.");setReview(data);if(data.printify)setManualId(data.printify.id);
 }catch(e){setReview(null);setError((e as Error).message);}finally{setBusy(false);lock.current=false;}}
 useEffect(()=>{void load();},[]);
 async function prepare(line:FulfillmentLine){if(lock.current)return;lock.current=true;setBusy(true);setError("");try{
  const r=await fetch("/api/printify/drafts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"prepare-order",orderId:orderId(),lineId:line.id})}),data=await r.json() as {transfer:Transfer;error?:string};if(!r.ok)throw new Error(data.error||"Could not prepare this artwork.");window.location.assign("/orders/printify?transfer="+data.transfer.id);
 }catch(e){setError((e as Error).message);setBusy(false);lock.current=false;}}
 async function approve(){if(!review?.ready||!review.printify||!confirmed||lock.current)return;lock.current=true;setBusy(true);setError("");try{
  const r=await fetch("/api/fulfillment",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"approve-artwork",orderId:review.orderId,printifyOrderId:review.printify.id,fingerprint:review.fingerprint,confirmed:true})}),data=await r.json() as Review&{error?:string};if(!r.ok)throw new Error(data.error||"Could not save this review.");setReview(data);setConfirmed(false);
 }catch(e){setReview(null);setError((e as Error).message);}finally{setBusy(false);lock.current=false;}}
 return <><div className="page-heading"><div><p className="eyebrow">FORGELINC / FULFILLMENT REVIEW</p><h1>From saved design to printed jersey.</h1><p>Prepare each jersey, match the original Printify order, then approve production in Printify.</p></div><button className="secondary-button" disabled={busy} onClick={()=>load(1,!!manualId.trim())}><RefreshCw size={17}/>{busy?"Checking…":"Refresh fulfillment"}</button></div>
 <section className="setup-card fulfillment-intro"><h2>Your approval stays in the loop</h2><p>Keep Printify order approval set to <strong>Manual</strong>. ForgeLinc prepares the personalized products and checks the imported order. You make the final production approval in Printify, where you can review shipping and fulfillment charges.</p><p>Use the existing imported Shopify order to keep its delivery and tracking connection. Do not create another order.</p></section>
 {error&&<section className="setup-card"><p className="connection-error" role="alert">{error}</p><button className="secondary-button" disabled={busy} onClick={()=>load(1,!!manualId.trim())}>Retry check</button><a className="text-link" href="/connect#printify">Printify connection settings</a></section>}
 {busy&&<p role="status">Checking the saved artwork and current order…</p>}
 {review&&<><section className="setup-card"><h2>{review.name}{review.test?" · Test order":""}</h2>{review.hold&&<p className="connection-error">{review.hold}</p>}<p className="fine-print">Checked {new Date(review.checkedAt).toLocaleString()}. Changes after this check require a fresh review.</p><h3>1. Prepare every purchased design</h3><div className="fulfillment-items">{review.lines.map(line=><article className="fulfillment-item" key={line.id}><div><h3>{line.artwork?.team.name??line.title}</h3>{line.artwork&&<><p>{themeLabel(line.artwork.config)} · {line.artwork.size} · Quantity {line.quantity}</p><p>Name: <strong>{line.artwork.config.playerName||"None"}</strong> · Number: <strong>{line.artwork.config.playerNumber||"None"}</strong></p><p>Front artwork: {line.artwork.config.frontLogoLabel}</p></>}{line.productTitle&&<p><strong>Use this prepared product in Printify:</strong><br/>{line.productTitle}<br/><small>Product ID: {line.productId}</small></p>}{line.issue&&<p className="connection-error">{line.issue}</p>}</div><div className="fulfillment-item-actions">{line.artwork&&<button className="secondary-button" onClick={()=>setOpen(open===line.id?null:line.id)} aria-expanded={open===line.id}>{open===line.id?"Close preview":"Review saved design"}</button>}{line.transferId?<a className="secondary-button" href={"/orders/printify?transfer="+line.transferId}>Review prepared artwork</a>:<button className="primary-button" disabled={busy||!!review.hold||!line.artwork} onClick={()=>prepare(line)}>Prepare Printify artwork</button>}</div>{open===line.id&&line.artwork&&<div className="fulfillment-artwork"><Jersey3D team={line.artwork.team} config={line.artwork.config} pending={false} unavailable={false} fallback={<p>Review the panel mockups in Printify.</p>}/></div>}</article>)}</div></section>
 {!review.test&&<><section className="setup-card"><h2>2. Match the imported Printify order</h2><ol className="fulfillment-steps"><li>Open order <strong>{review.name}</strong> in your connected Printify store and choose <strong>Edit order</strong>.</li><li>Add each prepared product listed above, with its purchased size and quantity. Two different names or designs need their own prepared products.</li><li>Remove the original unpersonalized jersey items. Save the order edits, keeping the order on hold.</li><li>Review the actual order’s front, back, sleeves, collar and delivery details. Return here and refresh the check.</li></ol><div className="fulfillment-actions"><a className="secondary-button" href={printifyOrders} target="_blank" rel="noreferrer">Open Printify orders <ExternalLink size={16}/></a><button className="primary-button" disabled={busy} onClick={()=>load(1,!!manualId.trim())}>Check updated order</button></div><p className="fine-print">Printify’s API does not replace items in an imported order. <a href="https://help.printify.com/hc/en-us/articles/4483630248465-How-do-I-cancel-or-edit-an-order" target="_blank" rel="noreferrer">Printify’s editing guide</a></p>
 {review.notice&&<p role="status">{review.notice}</p>}{review.nextSearchPage&&!review.printify&&<button className="secondary-button" disabled={busy} onClick={()=>load(review.nextSearchPage!)}>Search next page of Printify orders</button>}
 <details className="fulfillment-manual"><summary>Find a specific Printify order</summary><label htmlFor="printify-order-reference">Printify order ID</label><input id="printify-order-reference" value={manualId} maxLength={24} onChange={e=>setManualId(e.target.value)} placeholder="24-character ID from the order URL"/><button className="secondary-button" disabled={busy||!manualId.trim()} onClick={()=>load(1,true)}>Check this order</button><p className="fine-print">ForgeLinc checks that it belongs to this Shopify purchase before using it.</p></details>
 {review.printify&&<><h3>Printify order: {review.printify.label}</h3><p>Status: <strong>{review.printify.status.replaceAll("-"," ")}</strong> · ID: {review.printify.id}</p><div className="fulfillment-table-wrap"><table className="fulfillment-table"><thead><tr><th>Product in Printify order</th><th>Variant</th><th>Quantity</th></tr></thead><tbody>{review.printify.items.map((item,index)=><tr key={index}><td>{review.lines.find(l=>l.productId===item.productId)?.productTitle??"Unmatched product"}<br/><small>{item.productId}</small></td><td>{item.size||"See Printify"}</td><td>{item.quantity}</td></tr>)}</tbody></table></div>{review.printify.shipments.map((shipment,index)=><p key={index}>{shipment.carrier} · {shipment.number} {shipment.url&&<a href={shipment.url} target="_blank" rel="noreferrer">Track shipment</a>}</p>)}</>}
 {review.issues.map(issue=><p className="connection-error" key={issue}>{issue}</p>)}{review.ready&&<p className="order-match"><CheckCircle2 size={17}/>Products, sizes and quantities match the prepared jerseys.</p>}</section>
 <section className="setup-card"><h2>3. Record your artwork review</h2><p>ForgeLinc checks product references and the prepared print files. Your visual review confirms the artwork actually shown inside the Printify order, including names, numbers and seam placement.</p>{review.ready&&!review.reviewedAt&&<><label className="check-label fulfillment-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} disabled={busy}/>I reviewed every panel in the actual Printify order and confirmed the personalization, quantities and delivery details.</label><button className="primary-button" disabled={busy||!confirmed} onClick={approve}>Save artwork approval</button></>}{!review.ready&&<p>Resolve the checks above before recording your approval.</p>}{review.reviewedAt&&<div className="verified-connection"><CheckCircle2 size={20}/><div><strong>Artwork review saved</strong><p>{new Date(review.reviewedAt).toLocaleString()}</p><a className="primary-button" href={printifyOrders} target="_blank" rel="noreferrer">Open Printify for final production approval <ExternalLink size={16}/></a><p>Review the fulfillment and shipping charges there before submitting. This approval in ForgeLinc has not placed an order, charged you or started production.</p></div></div>}</section></>}
 </>}
 </>;
}
