"use client";
import {useEffect,useRef,useState} from "react";
import {Upload,Trash2} from "lucide-react";
import {uploadArtwork} from "@/lib/artwork-upload";
import {artworkPanels,artworkLayer,panels,panelLogoOptions,originalArtworkSource,themeLabel,isCustomTheme,type JerseyTheme,type PanelLogoOptions,type TeamLogoOptions,type Team,type TemplateConfig,type ArtworkPanel,type ArtworkChoice,type PanelChoices} from "@/lib/catalog";
export function ThemePicker({value,onChange,disabled=false,customThemes=[]}:{value:JerseyTheme;onChange:(theme:JerseyTheme)=>void;disabled?:boolean;customThemes?:TemplateConfig[]}){
 const choices=[{id:"light",name:"Light",color:"#fff"},{id:"dark",name:"Dark",color:"#101820"},...customThemes.map(c=>({id:c.jerseyTheme,name:themeLabel(c),color:c.shirtColor}))];
 return <div className="theme-picker"><div className="jersey-themes" role="group" aria-label="Jersey theme">{choices.map(theme=><button type="button" key={theme.id} aria-pressed={value===theme.id} disabled={disabled} onClick={()=>onChange(theme.id)}><span aria-hidden="true" style={{background:theme.color}}/>{theme.name}</button>)}</div></div>;
}
export function ThemeManager({config,themes,onCreate,onRename,onRemove,disabled}:{config:TemplateConfig;themes:TemplateConfig[];onCreate:(name:string,source:string)=>Promise<boolean>;onRename:(name:string)=>Promise<boolean>;onRemove:()=>Promise<void>;disabled:boolean}){
 const [name,setName]=useState(""),[source,setSource]=useState("current"),[rename,setRename]=useState(config.themeName),[error,setError]=useState("");
 const validName=(value:string,renaming=false)=>{if(!value.trim()){setError("Give this theme a name.");return false;}if(["light","dark"].includes(value.trim().toLowerCase())||themes.some(t=>(!renaming||t.jerseyTheme!==config.jerseyTheme)&&themeLabel(t).toLowerCase()===value.trim().toLowerCase())){setError("That name is already in use for this team.");return false;}setError("");return true;};
 return <div className="theme-manager"><details><summary>Create theme</summary><label>Theme name<input value={name} maxLength={80} placeholder="Fall Tournament" onChange={e=>setName(e.target.value)}/></label><label>Start with<select value={source} onChange={e=>setSource(e.target.value)}><option value="current">Copy current design</option><option value="fresh">Start fresh</option>{themes.filter(t=>t.jerseyTheme!==config.jerseyTheme).map(t=><option key={t.jerseyTheme} value={t.jerseyTheme}>{themeLabel(t)}</option>)}</select></label><button type="button" className="primary-button full" disabled={disabled} onClick={async()=>{if(validName(name)&&await onCreate(name.trim(),source))setName("");}}>Create and save theme</button><p className="fine-print">Each team can have as many named themes as you need. Copying includes colors, artwork and placement.</p></details>
 {isCustomTheme(config.jerseyTheme)&&<details><summary>Manage this theme</summary><label>Theme name<input value={rename} maxLength={80} onChange={e=>setRename(e.target.value)}/></label><button type="button" className="secondary-button full" disabled={disabled} onClick={async()=>{if(validName(rename,true))await onRename(rename.trim());}}>Rename and save theme</button><details className="remove-theme"><summary>Remove this theme…</summary><p>Remove this theme from this team’s choices? Saved custom selections, artwork files and Printify transfers stay intact.</p><button type="button" className="secondary-button full" disabled={disabled} onClick={onRemove}>Remove theme</button></details></details>}{error&&<p role="alert" className="connection-error">{error}</p>}</div>;
}
type UploadProps={label:string;onUpload:(asset:{id:string;name:string})=>void;disabled?:boolean;onBusy?:(busy:boolean)=>void};
export function LogoUpload({label,onUpload,disabled=false,onBusy}:UploadProps){
 const [busy,setBusy]=useState(false),[error,setError]=useState("");const input=useRef<HTMLInputElement>(null),alive=useRef(true),busyCallback=useRef(onBusy);busyCallback.current=onBusy;
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;busyCallback.current?.(false);};},[]);
 async function upload(file:File){setBusy(true);onBusy?.(true);setError("");try{const asset=await uploadArtwork(file);if(alive.current)onUpload(asset);}catch(e){if(alive.current)setError((e as Error).message);}finally{if(alive.current){setBusy(false);onBusy?.(false);if(input.current)input.current.value="";}}}
 return <div className="logo-upload"><input ref={input} type="file" accept="image/png,image/jpeg" hidden onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);}}/><button type="button" className="secondary-button full" disabled={disabled||busy} onClick={()=>input.current?.click()}><Upload size={16}/>{busy?"Uploading…":label}</button>{error&&<p role="alert" className="connection-error">{error}</p>}</div>;
}
function ArtworkThumb({src,label}:{src:string|null;label:string}){return src?<img src={src} alt=""/>:<span className="artwork-empty-thumb">{label}</span>;}
export function LogoLibrary({options,onChange,onSave,onUse,onOriginal,onSavedDefault,currentAssetId,disabled,panel,team,config}:{options:PanelLogoOptions;onChange:(value:PanelLogoOptions)=>void;onSave:()=>void;onUse:(id:string,name:string)=>void;onOriginal:()=>void;onSavedDefault:()=>void;currentAssetId?:string|null;disabled:boolean;panel:ArtworkPanel;team:Team;config:TemplateConfig}){
 const [busy,setBusy]=useState(false),panelName=panels.find(p=>p.id===panel)!.name,original=originalArtworkSource(team,config,panel);
 return <fieldset className="team-logo-library panel-artwork-library" disabled={disabled||busy}><div className="library-heading"><h3>{panelName} artwork choices</h3><span>Shared across this team’s themes</span></div><p>Add choices without changing your template. “Use on this template” applies an image; save the team template to make it the default.</p>
 <div className="library-choice-grid"><div className="library-choice original-choice"><ArtworkThumb src={original} label={panel==="collar"?"Original stripes":"No artwork"}/><strong>Original artwork</strong><small>Always available in your builder</small><button type="button" className="secondary-button full" onClick={onOriginal}>Use original</button></div>
 {options.logos.map(logo=><div className="library-choice" key={logo.id}><ArtworkThumb src={"/api/artwork/"+logo.assetId} label={logo.name}/><input aria-label={panelName+" alternate name"} value={logo.name} maxLength={80} onChange={e=>onChange({...options,logos:options.logos.map(l=>l.id===logo.id?{...l,name:e.target.value}:l)})}/><button type="button" className="secondary-button full" disabled={!logo.name.trim()} onClick={()=>onUse(logo.assetId,logo.name)}>{currentAssetId===logo.assetId?"In this template":"Use on this template"}</button><button type="button" className="text-link remove-logo" onClick={()=>onChange({...options,logos:options.logos.filter(l=>l.id!==logo.id)})}><Trash2 size={16}/>Remove choice</button></div>)}</div>
 <div className="library-actions"><button type="button" className="secondary-button" onClick={onSavedDefault}>Use saved template default</button><LogoUpload label={"Add "+panelName.toLowerCase()+" alternate"} disabled={disabled||options.logos.length>=12} onBusy={setBusy} onUpload={asset=>onChange({...options,logos:[...options.logos,{id:crypto.randomUUID(),assetId:asset.id,name:asset.name.replace(/\.[^.]+$/,"").slice(0,80)||"Alternate artwork"}]})}/>
 {currentAssetId&&!options.logos.some(l=>l.assetId===currentAssetId)&&<button type="button" className="secondary-button" disabled={options.logos.length>=12} onClick={()=>onChange({...options,logos:[...options.logos,{id:crypto.randomUUID(),assetId:currentAssetId,name:panel==="front"?config.frontLogoLabel:"Saved "+panelName.toLowerCase()+" artwork"}]})}>Add current image to choices</button>}
 <button type="button" className="primary-button" onClick={onSave} disabled={options.logos.some(l=>!l.name.trim())}>Save artwork choices</button></div>
 <div className="library-shop-controls"><label className="check-label"><input type="checkbox" checked={options.offerOriginal!==false} onChange={e=>onChange({...options,offerOriginal:e.target.checked})}/>Offer original to shoppers</label><label className="check-label"><input type="checkbox" checked={options.allowUploads} onChange={e=>onChange({...options,allowUploads:e.target.checked})}/>Allow shoppers to upload for this panel</label></div>
 <small>Up to 12 alternates per panel. Removing a choice keeps saved designs and the original artwork intact.</small>{panel==="collar"&&<p>Collar artwork is very small on the finished jersey. Check its placement in Printify.</p>}</fieldset>;
}
export function ShopperArtworkChoices({team,config,options,choices,onSelect,onBusy,disabled,busy,defaultLabel}:{team:Team;config:TemplateConfig;options:TeamLogoOptions;choices:PanelChoices;defaultLabel?:string;onSelect:(panel:ArtworkPanel,choice:ArtworkChoice|null)=>void;onBusy:(busy:boolean)=>void;disabled:boolean;busy:boolean}){
 return <div className="shopper-artwork-options"><h3>Choose your artwork</h3>{artworkPanels.map(panel=>{
  const policy=panelLogoOptions(options,panel),layer=artworkLayer(config,panel),name=panels.find(p=>p.id===panel)!.name,original=originalArtworkSource(team,config,panel),selected=choices[panel];
  const valid=selected?.id==="original"?(policy.offerOriginal!==false?selected:undefined):selected?.id==="upload"?(policy.allowUploads?selected:undefined):policy.logos.find(l=>l.id===selected?.id&&l.assetId===selected?.assetId);
  const source=layer.visible?(layer.assetId?"/api/artwork/"+layer.assetId:original):null;
  const originalIsDefault=!layer.assetId&&layer.visible===!!original;
  return <details key={panel} className="shopper-panel-options" open={panel==="front"}><summary>{name}<span>{valid?.name??defaultLabel??"Template default"}</span></summary><div className="front-logo-choices" role="group" aria-label={name+" artwork choices"}>
  <button type="button" aria-pressed={!valid||(valid.id==="original"&&originalIsDefault)} disabled={disabled||busy} onClick={()=>onSelect(panel,null)}><ArtworkThumb src={source} label={panel==="collar"?"Stripes":"No artwork"}/><span>{defaultLabel??(originalIsDefault?"Original / default":"Template default")}</span></button>
  {!originalIsDefault&&policy.offerOriginal!==false&&<button type="button" aria-pressed={valid?.id==="original"} disabled={disabled||busy} onClick={()=>onSelect(panel,{id:"original",name:"Original artwork"})}><ArtworkThumb src={original} label={panel==="collar"?"Stripes":"No artwork"}/><span>Original artwork</span></button>}
  {policy.logos.map(l=><button type="button" key={l.id} aria-pressed={valid?.id===l.id} disabled={disabled||busy} onClick={()=>onSelect(panel,l)}><ArtworkThumb src={"/api/artwork/"+l.assetId} label={l.name}/><span>{l.name}</span></button>)}
  {valid?.id==="upload"&&valid.assetId&&<button type="button" aria-pressed="true" disabled={disabled||busy}><ArtworkThumb src={"/api/artwork/"+valid.assetId} label={valid.name}/><span>{valid.name}</span></button>}</div>
  {policy.allowUploads&&<LogoUpload label={"Upload my own "+name.toLowerCase()+" artwork"} disabled={disabled||busy} onBusy={onBusy} onUpload={asset=>onSelect(panel,{id:"upload",assetId:asset.id,name:asset.name.replace(/\.[^.]+$/,"").slice(0,80)||"Custom artwork"})}/>}
  {!policy.logos.length&&!policy.allowUploads&&<p className="fine-print">This panel uses the team’s saved design.</p>}</details>})}<p className="fine-print">Each choice updates its own panel. PNG keeps a transparent background.</p></div>;
}
