"use client";
import {useEffect,useState} from "react";
import type {CheckoutProduct} from "@/lib/checkout-types";
type Status={configured:boolean;ready:boolean;settings:{productId:string;price:string}|null;product:CheckoutProduct|null;error:string|null;publicationNotice?:string;providerSizes?:string[];grantedScopes?:string[];jobs?:{id:string;state:string;message:string|null;printify_order_id:string|null}[]};
export default function ShopifyCheckoutCard(){
 const [status,setStatus]=useState<Status|null>(null),[price,setPrice]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){setBusy(true);setError("");try{const r=await fetch("/api/checkout",{cache:"no-store"}),s=await r.json() as Status;if(!r.ok)throw new Error(s.error||"Could not verify checkout.");setStatus(s);if(s.settings)setPrice(s.settings.price);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void load();},[]);
 async function setup(){setBusy(true);setError("");try{const r=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"setup",...(price?{price}: {})})}),s=await r.json() as Status;if(!r.ok)throw new Error(s.error||"Could not verify checkout.");setStatus(s);setPrice(s.settings?.price??price);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="setup-card checkout-setup" id="checkout"><span className="step-number">03</span><h2>All-team custom checkout</h2><p>Every saved team and theme uses this jersey’s size options. Each order gets its own exact artwork in Printify.</p><label htmlFor="custom-jersey-price">Jersey selling price (USD)</label><input id="custom-jersey-price" type="number" min="1" max="1000" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} placeholder="Use the current linked jersey price" disabled={busy}/><div className="transfer-actions"><button className="primary-button" disabled={busy} onClick={setup}>{busy?"Checking checkout…":status?.configured?"Sync sizes and price":"Set up all-team checkout"}</button><button className="secondary-button" disabled={busy} onClick={load}>Refresh status</button></div>{(error||status?.error)&&<p className="connection-error" role="alert">{error||status?.error}</p>}{status?.publicationNotice&&<p role="status">{status.publicationNotice}</p>}{status?.settings&&<a className="text-link" href={"https://admin.shopify.com/store/eewwjf-tt/products/"+status.settings.productId.split("/").pop()} target="_blank" rel="noreferrer">Open shared checkout product in Shopify</a>}{status?.providerSizes?.length&&<p>Printify sizes: {status.providerSizes.join(" · ")}</p>}{status?.grantedScopes&&status.grantedScopes.length>0&&!status.ready&&<p className="fine-print">Shopify permissions: {status.grantedScopes.join(", ")}</p>}{status?.product&&<><h3>{status.ready?"Checkout sizes verified":"Checkout needs attention"}</h3><ul>{status.product.variants.map(v=><li key={v.id}>{v.size} — {v.currency} {v.amount}{!v.available&&" · Unavailable"}</li>)}</ul></>}<p className="fine-print">The shared product handles sizes and pricing. Checkout uploads the five panels before payment. Existing team products are preserved.</p><a className="text-link" href="/orders">Custom order status</a></section>;
}
