"use client";
import {useEffect,useState} from "react";
import {CHECKOUT_PRODUCT_ID,type CheckoutStatus} from "@/lib/checkout-types";
export default function ShopifyCheckoutCard(){
 const [status,setStatus]=useState<CheckoutStatus|null>(null),[productId,setProductId]=useState(CHECKOUT_PRODUCT_ID),[token,setToken]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){setBusy(true);setError("");try{const r=await fetch("/api/shopify-checkout",{cache:"no-store"}),s=await r.json() as CheckoutStatus&{error?:string};if(!r.ok)throw new Error(s.error);setStatus(s);setProductId(s.productId);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{load();},[]);
 async function save(){setBusy(true);setError("");try{const r=await fetch("/api/shopify-checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"configure",settings:{productId,...(token.trim()?{token:token.trim()}:{})}})}),s=await r.json() as CheckoutStatus&{error?:string};if(!r.ok)throw new Error(s.error);setStatus(s);setToken("");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const product=status?.product;
 return <section className="setup-card checkout-setup" id="checkout"><span className="step-number">03</span><h2>Connect the published jersey</h2><p>Link Dayton Eagles to its Shopify sizes, pricing and checkout.</p><label htmlFor="checkout-product-id">Shopify product ID</label><input id="checkout-product-id" value={productId} onChange={e=>setProductId(e.target.value.replace(/\D/g,""))} disabled={busy}/><a className="text-link" href={"https://admin.shopify.com/store/eewwjf-tt/products/"+productId} target="_blank" rel="noreferrer">Open product in Shopify</a><label htmlFor="checkout-storefront-token">Public Storefront API token {status?.tokenConfigured?"(saved)":"(if required)"}</label><input id="checkout-storefront-token" type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} placeholder={status?.tokenConfigured?"Leave blank to keep the saved token":"From your Shopify Headless channel"} disabled={busy}/><p className="fine-print">Use the public Storefront token, not the ForgeLinc Client secret. Make this product available to the same storefront channel.</p><div className="transfer-actions"><button className="primary-button" disabled={busy||!productId} onClick={save}>{busy?"Checking Shopify…":"Save and verify product"}</button><button className="secondary-button" disabled={busy} onClick={load}>Refresh</button></div>{(error||status?.error)&&<p className="connection-error" role="alert">{error||status?.error}</p>}{status?.adminProduct&&<p><strong>{status.adminProduct.title}</strong><br/>Shopify status: {status.adminProduct.status}<br/>Published product variants: {status.adminProduct.sizes.join(", ")}</p>}{product&&<><h3>{status?.ready?"Ready for an admin checkout preview":"No purchasable sizes"}</h3><ul>{product.variants.map(v=><li key={v.id}>{v.size} — {v.currency} {v.amount}{!v.available&&" · Unavailable"}</li>)}</ul></>}<p className="fine-print">Customer checkout stays closed while personalized print fulfillment is being connected. You can test a Dayton Eagles design from the preview bag; do not complete payment yet.</p><a className="text-link" href="/?team=dayton-eagles">Customize Dayton Eagles</a></section>;
}
