"use client";
import {stripeLayout} from "@/lib/stripe-layout";
import {useState} from "react";
import {uploadArtwork} from "@/lib/artwork-upload";
import type {TemplateConfig} from "@/lib/catalog";
const styles=[{id:"sweep",name:"Sweeps"},{id:"angular",name:"Angles"},{id:"curved",name:"Waves"},{id:"straight",name:"Straight"},{id:"lightning",name:"Lightning"},{id:"twist",name:"Twisted ribbons"},{id:"blade-bolts",name:"Blade bolts"},{id:"pixels",name:"Pixels"},{id:"digital-camo",name:"Digital Camo"},{id:"none",name:"No stripes"},{id:"custom",name:"My image"}] as const;
export default function StripeControls({config,onChange}:{config:TemplateConfig;onChange:(fn:(c:TemplateConfig)=>TemplateConfig)=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState("");
 async function upload(file:File){setBusy(true);setError("");try{const asset=await uploadArtwork(file);onChange(c=>({...c,stripeStyle:"custom",stripeAssetId:asset.id}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="stripe-controls"><label>Bottom &amp; sleeve shape</label><div className="stripe-style-choices" role="group" aria-label="Bottom and sleeve shape">{(["wedges","bands"] as const).map(layout=><button type="button" key={layout} disabled={busy} aria-pressed={stripeLayout(config)===layout} className={stripeLayout(config)===layout?"active":""} onClick={()=>onChange(c=>({...c,stripeLayout:layout}))}>{layout==="wedges"?"Wedges":"Bands"}</button>)}</div><p className="fine-print">Wedges fill the corners and rise up the sides. Bands run across the bottom.</p>{stripeLayout(config)==="bands"&&config.stripeStyle!=="none"&&<><label className="artwork-range">Band height<output>{Math.round((config.bandHeight??.18)*100)}%</output><input type="range" aria-label="Band height" min="8" max="40" step="1" value={Math.round((config.bandHeight??.18)*100)} disabled={busy} onChange={e=>{const height=Number(e.target.value)/100;onChange(c=>({...c,bandHeight:height}));}}/></label><p className="fine-print">Adjusts the bottom and sleeve bands. Back artwork stays in front of the band.</p></>}<label>Bottom &amp; sleeve style</label><div className="stripe-style-choices" role="group" aria-label="Matching bottom and sleeve stripes">{styles.map(s=><button type="button" key={s.id} disabled={busy} aria-pressed={config.stripeStyle===s.id} className={config.stripeStyle===s.id?"active":""} onClick={()=>onChange(c=>({...c,stripeStyle:s.id,stripeLayout:stripeLayout(c)}))}>{s.name}</button>)}</div><p className="fine-print">Sleeves match the shape, style and colors. Save each team theme to keep its choices.</p>{config.stripeStyle==="custom"&&<><label htmlFor="stripe-artwork">Upload bottom &amp; sleeve design</label><input id="stripe-artwork" type="file" accept="image/png,image/jpeg" disabled={busy} onChange={e=>{const f=e.target.files?.[0];e.target.value="";if(f)upload(f);}}/>{busy&&<p role="status">Uploading design…</p>}{config.stripeAssetId?<><img className="stripe-artwork-preview" src={"/api/artwork/"+config.stripeAssetId} alt="Custom stripe design"/><button type="button" className="text-link" onClick={()=>onChange(c=>({...c,stripeAssetId:null,stripeStyle:"none"}))}>Remove stripe image</button></>:<p className="fine-print">Upload a wide image. Transparent PNG keeps the shirt color visible.</p>}<p className="fine-print">Your image wraps the lower panels and sleeves. Its original colors are kept.</p></>}{error&&<p role="alert" className="connection-error">{error}</p>}</div>;
}
