"use client";
import {useState} from "react";
import {Plus,Loader2} from "lucide-react";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {uploadArtwork} from "@/lib/artwork-upload";
import type {CustomTeam} from "@/lib/catalog";
export default function TeamManager({disabled,onSave,existing}:{disabled:boolean;onSave:(team:CustomTeam)=>Promise<boolean>;existing?:CustomTeam}){
 const [open,setOpen]=useState(false),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [value,setValue]=useState<CustomTeam>({id:"",name:"",kind:"team",primary:"#092c49",accent:"#cc1428",logoAssetId:null,backAssetId:null});
 function start(edit=false){setEditing(edit);setError("");setValue(edit&&existing?{...existing}:{id:"custom-team-"+crypto.randomUUID(),name:"",kind:"team",primary:"#092c49",accent:"#cc1428",logoAssetId:null,backAssetId:null});setOpen(true);}
 async function upload(file:File,key:"logoAssetId"|"backAssetId"){setBusy(true);setError("");try{const asset=await uploadArtwork(file);setValue(v=>({...v,[key]:asset.id}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(){setBusy(true);setError("");try{if(await onSave({...value,name:value.name.trim()}))setOpen(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div className="team-manager-actions"><button type="button" className="text-link" disabled={disabled} onClick={()=>start()}><Plus size={16}/>Add team / collection</button>{existing&&<button type="button" className="text-link" disabled={disabled} onClick={()=>start(true)}>Edit team details</button>}</div><Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogContent className="team-manager-dialog"><DialogHeader><DialogTitle>{editing?"Edit team details":"Add team or collection"}</DialogTitle><DialogDescription>Keep its logos, colors and jersey themes together in ForgeLinc.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();save();}}><fieldset disabled={busy}><label htmlFor="new-team-name">Name</label><input id="new-team-name" required maxLength={80} value={value.name} onChange={e=>setValue(v=>({...v,name:e.target.value}))} placeholder="Team, tournament or league collection"/><label htmlFor="new-team-kind">Type</label><select id="new-team-kind" value={value.kind} onChange={e=>setValue(v=>({...v,kind:e.target.value as "team"|"league"}))}><option value="team">Team</option><option value="league">League / custom collection</option></select><div className="color-controls"><label>Base color<input type="color" value={value.primary} onChange={e=>setValue(v=>({...v,primary:e.target.value}))}/></label><label>Accent color<input type="color" value={value.accent} onChange={e=>setValue(v=>({...v,accent:e.target.value}))}/></label></div><div className="team-manager-art">{(["logoAssetId","backAssetId"] as const).map(key=><div key={key}><label htmlFor={key}>{key==="logoAssetId"?"Main logo":"Back artwork"}</label><img src={value[key]?"/api/artwork/"+value[key]:"/assets/mlbl.png"} alt={key==="logoAssetId"?"Main logo preview":"Back artwork preview"}/><input id={key} type="file" accept="image/png,image/jpeg" onChange={e=>{const f=e.target.files?.[0];e.target.value="";if(f)upload(f,key);}}/>{value[key]&&<button type="button" className="text-link" onClick={()=>setValue(v=>({...v,[key]:null}))}>Use MLBL badge</button>}</div>)}</div><p className="fine-print">Starts with the MLBL badge where no image is uploaded. You can replace it and add alternate artwork in the editor.</p>{error&&<p role="alert" className="connection-error">{error}</p>}<button className="primary-button full" disabled={busy||!value.name.trim()}>{busy?<Loader2 size={17} className="spin"/>:<Plus size={17}/>} {editing?"Save team details":"Create and edit jersey"}</button></fieldset></form></DialogContent></Dialog></>;
}
